# Generated by Django 5.2.18 on 2026-10-08 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Judul Event')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('category', models.CharField(choices=[('konferensi', 'Konferensi'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('sosialisasi', 'Sosialisasi')], max_length=20, verbose_name='Kategori')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Sedang Berlangsung'), ('upcoming', 'Akan Datang'), ('finished', 'Selesai')], default='upcoming', max_length=20, verbose_name='Status')),
                ('format', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10, verbose_name='Format')),
                ('date', models.DateTimeField(verbose_name='Tanggal Event')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Lokasi')),
                ('speaker', models.CharField(blank=True, max_length=200, verbose_name='Pembicara')),
                ('organizer_name', models.CharField(blank=True, max_length=200, verbose_name='Nama Penyelenggara')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Harga')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Kapasitas')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Gambar')),
                ('has_certificate', models.BooleanField(default=True, verbose_name='Sertifikat Digital')),
                ('has_recording', models.BooleanField(default=False, verbose_name='Rekaman/Materi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Penyelenggara')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Lunas'), ('free', 'Gratis'), ('refunded', 'Dikembalikan')], default='pending', max_length=20)),
                ('attended', models.BooleanField(default=False, verbose_name='Hadir')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registrasi Event',
                'verbose_name_plural': 'Registrasi Event',
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Jumlah')),
                ('method', models.CharField(choices=[('qris', 'QRIS'), ('transfer', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('free', 'Gratis')], max_length=20, verbose_name='Metode')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('success', 'Berhasil'), ('failed', 'Gagal'), ('refunded', 'Dikembalikan')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.eventregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('claimed', models.BooleanField(default=False, verbose_name='Diklaim')),
                ('claimed_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='events.event')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='events.eventregistration')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikat',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
