# Fungsi file: Migration app registrations: menambahkan attendance dan constraint-nya; operasi dan dependensi migration tetap dipertahankan.

# Generated by Django 5.2.17 on 2026-10-06 04:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('VOIDED', 'Voided')], default='PRESENT', max_length=7)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, max_length=2000)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='registrations.registration')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_attendances', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-checked_in_at', '-pk'),
                'permissions': [('scan_ticket', 'Can scan tickets for managed events'), ('void_attendance', 'Can void an attendance record')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'PRESENT'), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('status', 'VOIDED'), ('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='attendance_void_state_valid'), models.CheckConstraint(condition=models.Q(('voided_at__isnull', True), ('voided_at__gte', models.F('checked_in_at')), _connector='OR'), name='attendance_void_after_checkin')],
            },
        ),
    ]
