# Fungsi file: Migration app registrations: menambahkan feedback dan constraint rating; operasi dan dependensi migration tetap dipertahankan.

# Generated by Django 5.2.17 on 2026-10-06 04:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('material_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('speaker_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('organization_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('suggestion', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='registrations.registration')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('overall_rating__gte', 1), ('overall_rating__lte', 5)), name='feedback_overall_rating_range'), models.CheckConstraint(condition=models.Q(('material_rating__gte', 1), ('material_rating__lte', 5)), name='feedback_material_rating_range'), models.CheckConstraint(condition=models.Q(('speaker_rating__gte', 1), ('speaker_rating__lte', 5)), name='feedback_speaker_rating_range'), models.CheckConstraint(condition=models.Q(('organization_rating__gte', 1), ('organization_rating__lte', 5)), name='feedback_organization_rating_range')],
            },
        ),
    ]
