# Fungsi file: Migration app events: membentuk skema awal; operasi dan dependensi migration tetap dipertahankan.

# Generated by Django 5.2.17 on 2026-10-06 04:10

import apps.events.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
                ('description', models.TextField(max_length=20000)),
                ('delivery_mode', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], max_length=10)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=500)),
                ('capacity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('registration_open', models.DateTimeField()),
                ('registration_close', models.DateTimeField()),
                ('banner', models.ImageField(blank=True, upload_to=apps.events.models.banner_upload_path)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs revision'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventtype')),
            ],
            options={
                'ordering': ('start_datetime', 'pk'),
                'permissions': [('submit_event', 'Can submit an event'), ('review_event', 'Can approve, reject or request event revision'), ('publish_event', 'Can publish or unpublish an event'), ('complete_event', 'Can complete an event'), ('cancel_event', 'Can cancel an event')],
            },
        ),
        migrations.CreateModel(
            name='EventAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('instructions', models.TextField(blank=True, max_length=5000)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_access', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs revision'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs revision'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('reason', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_transitions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='events.event')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('from_status__in', ['DRAFT', 'SUBMITTED', 'NEEDS_REVISION', 'APPROVED', 'PUBLISHED', 'COMPLETED', 'REJECTED', 'CANCELLED']), ('to_status__in', ['DRAFT', 'SUBMITTED', 'NEEDS_REVISION', 'APPROVED', 'PUBLISHED', 'COMPLETED', 'REJECTED', 'CANCELLED']), models.Q(('from_status', models.F('to_status')), _negated=True)), name='event_transition_states_valid'), models.CheckConstraint(condition=models.Q(models.Q(('to_status__in', ['NEEDS_REVISION', 'REJECTED', 'CANCELLED']), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='event_transition_reason_required')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_datetime'], name='event_public_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'status'], name='event_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('registration_open__lt', models.F('registration_close')), ('registration_close__lte', models.F('start_datetime'))), name='event_registration_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='event_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='event_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'NEEDS_REVISION', 'APPROVED', 'PUBLISHED', 'COMPLETED', 'REJECTED', 'CANCELLED'])), name='event_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_mode__in', ['OFFLINE', 'ONLINE', 'HYBRID'])), name='event_delivery_mode_valid'),
        ),
    ]
