# Fungsi file: Migration app achievements: membentuk skema awal; operasi dan dependensi migration tetap dipertahankan.

# Generated by Django 5.2.17 on 2026-10-07 03:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_seed_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('required_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='events.eventtype')),
            ],
            options={
                'ordering': ('required_count', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qualifying_count', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_awards', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-awarded_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.CheckConstraint(condition=models.Q(('required_count__gt', 0)), name='achievement_required_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='user_achievement_unique_assignment'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.CheckConstraint(condition=models.Q(('qualifying_count__gt', 0)), name='user_achievement_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False)), _connector='OR'), name='user_achievement_active_state_valid'),
        ),
    ]
