# Fungsi file: Migration app achievements: menambahkan reward dan kebijakan diskon event; operasi dan dependensi migration tetap dipertahankan.

# Generated by Django 5.2.17 on 2026-10-07 03:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('events', '0002_seed_event_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRewardPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_achievement_discount', models.BooleanField(default=False)),
                ('max_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_policy', to='events.event')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('accept_achievement_discount', False), ('max_discount_percentage', 0)), models.Q(('accept_achievement_discount', True), ('max_discount_percentage__gt', 0), ('max_discount_percentage__lte', 100)), _connector='OR'), name='event_reward_policy_valid')],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('achievement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reward', to='achievements.achievement')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='reward_percentage_valid')],
            },
        ),
    ]
