# Fungsi file: Migration app partnerships: membentuk skema awal; operasi dan dependensi migration tetap dipertahankan.

# Generated by Django 5.2.17 on 2026-10-05 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options_accountaccesschange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_information', models.CharField(max_length=500)),
                ('proposal_text', models.TextField(max_length=10000)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs revision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizer_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'permissions': [('review_proposal', 'Can review organizer proposals')],
            },
        ),
        migrations.CreateModel(
            name='ProposalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs revision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs revision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_change', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountaccesschange')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_reviews', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='partnerships.organizerproposal')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='organizerproposal',
            index=models.Index(fields=['status', 'submitted_at'], name='proposal_review_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizerproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('DRAFT', 'SUBMITTED', 'NEEDS_REVISION'))), fields=('applicant',), name='proposal_one_open_per_user'),
        ),
        migrations.AddConstraint(
            model_name='organizerproposal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'NEEDS_REVISION', 'APPROVED', 'REJECTED'])), name='proposal_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='organizerproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), ('submitted_at__isnull', True)), models.Q(models.Q(('status', 'DRAFT'), _negated=True), ('submitted_at__isnull', False)), _connector='OR'), name='proposal_submission_time_valid'),
        ),
        migrations.AddConstraint(
            model_name='proposalreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_status__in', ['DRAFT', 'NEEDS_REVISION']), ('to_status', 'SUBMITTED')), models.Q(('from_status', 'SUBMITTED'), ('to_status__in', ['APPROVED', 'NEEDS_REVISION', 'REJECTED'])), _connector='OR'), name='proposal_review_transition_valid'),
        ),
        migrations.AddConstraint(
            model_name='proposalreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('to_status__in', ['NEEDS_REVISION', 'REJECTED']), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='proposal_review_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='proposalreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_change__isnull', False), ('to_status', 'APPROVED')), models.Q(models.Q(('to_status', 'APPROVED'), _negated=True), ('access_change__isnull', True)), _connector='OR'), name='proposal_approval_access_required'),
        ),
    ]
