# Fungsi file: Migration app accounts: menambahkan permission akun dan riwayat perubahan akses; operasi dan dependensi migration tetap dipertahankan.

# Generated by Django 5.2.17 on 2026-10-05 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_organizer', 'Can access organizer functionality'), ('manage_platform', 'Can access global platform administration'), ('manage_organizer_access', 'Can grant and revoke organizer access'), ('manage_accounts', 'Can suspend and activate participant accounts')]},
        ),
        migrations.CreateModel(
            name='AccountAccessChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANT_ORGANIZER', 'Grant organizer'), ('REVOKE_ORGANIZER', 'Revoke organizer'), ('SUSPEND', 'Suspend account'), ('ACTIVATE', 'Activate account')], max_length=20)),
                ('reason', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_access_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['GRANT_ORGANIZER', 'REVOKE_ORGANIZER', 'SUSPEND', 'ACTIVATE'])), name='accounts_access_action_valid'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='accounts_access_reason_required')],
            },
        ),
    ]
